---
title: Using the DP-Next theme
---

This guide walks you through adding the DP-Next theme to a repository
that uses Quarto.

The DP-Next theme is a
[Quarto brand extension](https://quarto.org/docs/extensions/brand.html),
which you can install and use in your project. The extension provides
the theme's styling (brand) as well as default website settings, such as
the navbar, search bar, and page footer.

## Before you begin

Make sure you have [Quarto](https://quarto.org/docs/get-started/)
installed with version **1.8.0 or later**. Check your version by running
`quarto --version` in a terminal.

To add the DP-Next theme to your project, you need to have a Git
repository set up locally on your computer. So either:

1. Create a Git repository locally.
2. Create a Git repository on GitHub and clone it to your computer.
3. Clone an existing repository to your computer if you don't have it on
   your computer.
4. Pull the latest changes from an existing repository if you have the
   repository on your computer already.

## Add the theme to your project

To add the DP-Next theme to your project, run the following command in
the terminal while in the root (working directory) of your project. You
can either enter the working directory by opening a terminal and using
`cd` or by opening the project in RStudio or VS Code and using the
terminal in those apps.

```bash
quarto add dp-next/dp-next-theme
```

This command adds the DP-Next theme to your project in the
`_extensions/` folder. In the `_extensions/dp-next/dp-next-theme/`
folder, you can find the theme files as well as images such as logos.

Then, open your `_quarto.yml` file and change the "type" of your project
to `dp-next-theme`, which looks like:

```{.yaml filename="_quarto.yml"}
project:
  type: dp-next-theme
```

This will apply the DP-Next theme to your project, including the
default website settings.

## Update the theme

To update the `dp-next-theme`, run:

``` bash
quarto update dp-next/dp-next-theme
```

This replaces the files in `_extensions/dp-next/dp-next-theme/` with the
newest version from the `dp-next-theme` repository. Commit the updated
extension files to the Git history and push to GitHub so that your
rendered output can use the theme :tada:

## Getting help

If you have any questions about using the DP-Next theme, please reach
out by opening an
[issue](https://github.com/dp-next/dp-next-theme/issues/new) in the
`dp-next-theme` GitHub repository.
